import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Sidebar from "./components/Sidebar/page";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./AuthProvider/AuthProvider";
export const metadata = {
  title: "Chat Fusion",
  description: "Generated by create next app",
};

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className}`}>
        <AuthProvider>
          <Navbar />
          <div className="flex">
            <div className="w-[300px] lg:block hidden">
              <Sidebar />
            </div>
            <div className="flex-1">{children}</div>
          </div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
