import { Rajdhani } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Chat Fusion",
  description: "Generated by create next app",
};

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className}`}>{children}</body>
    </html>
  );
}
