import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Sidebar from "./components/Sidebar/page";

export const metadata = {
  title: "Chat Fusion",
  description: "Generated by create next app",
};

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className}`}>
        <Navbar />
        <div className="flex">
          <div className="w-[300px] lg:block hidden">
            <Sidebar />
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
